### ISSUE TITLE
Rotating image

### ISSUE THREAD

**Issue by riya-17** [riya-17/FaceRecognition#13]
Rotate the images to 90 or 180 degree angles.

**Comment by stevenbw** [comment]
Hi @riya-17 is this issue still open? If so I'd like to work on it :)

**Comment by riya-17** [comment]
Hello @stevenbw yaa sure this issue is still open and you can contribute for this issue.

**Comment by kingseche** [comment]
Hi @riya-17 is this issue still open now ? If so i would like to give it a try. Thank you

**Comment by riya-17** [comment]
Hello @kingseche sorry for late reply this issue is open you can give it a try.. thank you

**Comment by darien-schettler** [comment]
Hi is this issue still available? If so I would love to give it a try. Thanks!

**Comment by GeorgeDubuque** [comment]
Hey @darien-schettler are you still working on this one?
