### ISSUE TITLE
Zoom-in or Zoom-out image

### ISSUE THREAD

**Issue by riya-17** [riya-17/FaceRecognition#14]
increase or decrease the size of image

**Comment by riya-17** [comment]
Firstly you can try to zoom-out or zoom-in for one step than you can try for adjustable.

**Comment by petergeorgas** [comment]
Mind if I give this a shot?

**Comment by riya-17** [comment]
@petergeorgas yaa sure this issue is open and you can try.

**Comment by enahsor** [comment]
I'm going to attempt this

**Comment by riya-17** [comment]
@enahsor Yaa sure this issue is open

**Comment by kingseche** [comment]
Hi again ! Is this issue also open ?

**Comment by riya-17** [comment]
Hi @kingseche sorry for late reply yes this issue is open you can contribute on it
