### ISSUE TITLE
RuntimeError: Unable to open complete_path/shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by gopal151295** [riya-17/FaceRecognition#19]
I am getting this error while running FaceRecognizer.py
```
Traceback (most recent call last):
  File "FaceRecognizer.py", line 67, in <module>
    predictor = dlib.shape_predictor(args["shape_predictor"])
RuntimeError: Unable to open complete_path/shape_predictor_68_face_landmarks.dat
```

Although I followed the steps to build and install dlib and I guess it is installed successfully.

```
>>> import dlib
>>> print(dlib.__version__)
19.17.0
```
what am i missing?

**Comment by rishav1802** [comment]
try adding the actual path in place of "complete path" :-)

**Comment by kshitijkhune** [comment]
I am also getting the same error i.e 

> Traceback (most recent call last):
>   File "FaceRecognizer.py", line 67, in <module>
>     predictor = dlib.shape_predictor(args["shape_predictor"])
> RuntimeError: Unable to open complete_path/shape_predictor_68_face_landmarks.dat


I tried with this two paths.
1. python FaceRecognizer.py shape_predictor_68_face_landmarks.dat
2. Python FaceRecognizer.py C:\Users\PycharmProject\shape_predictor_68_face_landmarks.dat

Please help me so i can run this
thank you

**Comment by rishav1802** [comment]
Try adding the path by default i.e., in the code itself
also there will be a forward slash before the  .dat file name

**Comment by riya-17** [comment]
@gopal151295  Is your problem solved?

**Comment by programmist87** [comment]
Добрый день. Вы можете подсказать, что это за файл, shape_predictor_68_face_landmarks.dat? Появился на смартфоне. Его создаёт какое-то определённое приложение? Или его создают разные приложения?
