### ISSUE TITLE
Automatization of requirements installation

### ISSUE THREAD

**Issue by kedMertens** [riya-17/FaceRecognition#7]
Hi, @riya-17 !
I would like to contribute to the project! 
The proposition is to wrap all required installation steps to requirements.txt and call pip just once as follows: `pip install -r requirements.txt` 
What do you think about it?
I could add this file and fix description on main page.

**Comment by riya-17** [comment]
Hello, @kedMertens 
I am happy as you want to contribute to this project. 
The proposed idea is really good as this will reduce the complexity and repeatition of same statements.
You can surely work on that :)

**Comment by kedMertens** [comment]
I'm on it then!

**Comment by riya-17** [comment]
@kedMertens 
Thanks for you Pull Request. It is working great :)

**Comment by kedMertens** [comment]
> @kedMertens
> Thanks for your Pull Request. It is working great :)

Thank you! It was my very first contribution to open source project : )
